### ISSUE TITLE
resource contention

### ISSUE THREAD

**Issue by majorseitan** [FINNGEN/pheweb#212]
multiple calls to the API results in errors
benchmark requests
clean up error

**Comment by majorseitan** [comment]
This is due to multi threading issues with pysam

https://www.biostars.org/p/275974/
https://pysam.readthedocs.io/en/latest/faq.html

**Comment by majorseitan** [comment]
add multiple_iterators = True to fetch

**Comment by majorseitan** [comment]
[2022-05-19 02:15:06,902] ERROR in app: Exception on /api/gene_phenos/TCF7L2 [GET]                                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app                                                                                                                                                          
    response = self.full_dispatch_request()                                                                                                                                                                                                                                    
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request                                                                                                                                             
    rv = self.handle_user_exception(e)                                                                                                                                                                                                                                         
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function                                                                                                                                        
    return cors_after_request(app.make_response(f(*args, **kwargs)))                                                                                                                                                                                                           
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request                                                                                                                                             
    rv = self.dispatch_request()                                                                                                                                                                                                                                               
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request                                                                                                                                                  
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                                                                                                                                               
  File "/home/mwm1/Work/pheweb/pheweb/serve/server.py", line 236, in api_gene_phenotypes                                                                                                                                                                                       
    phenotypes = [res for res in jeeves.gene_phenos(gene) if res.pheno['phenocode'] in use_phenos]                                                                                                                                                                             
  File "/home/mwm1/Work/pheweb/pheweb/serve/server_jeeves.py", line 104, in gene_phenos                                                                                                                                                                                        
    results = self.result_dao.get_top_per_pheno_variant_results_range(chrom, start, end)                                                                                                                                                                                       
  File "/home/mwm1/Work/pheweb/pheweb/serve/data_access/db.py", line 894, in get_top_per_pheno_variant_results_range                                                                                                                                                           
    pval = split[pheno[1]]                                                                                                                                                                                                                                                     
IndexError: list index out of range                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                             
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app                                                                                                                                                          
    response = self.full_dispatch_request()                                                                                                                                                                                                                                    
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request                                                                                                                                             
    rv = self.handle_user_exception(e)                                                                                                                                                                                                                                         
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function                                                                                                                                        
    return cors_after_request(app.make_response(f(*args, **kwargs)))                                                                                                                                                                                                           
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request                                                                                                                                             
    rv = self.dispatch_request()                                                                                                                                                                                                                                               
  File "/home/mwm1/Work/pheweb/.direnv/python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request                                                                                                                                                  
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)                                                                                                                                                                                               
  File "/home/mwm1/Work/pheweb/pheweb/serve/server.py", line 236, in api_gene_phenotypes                                                                                                                                                                                       
    phenotypes = [res for res in jeeves.gene_phenos(gene) if res.pheno['phenocode'] in use_phenos]                                                                                                                                                                             
  File "/home/mwm1/Work/pheweb/pheweb/serve/server_jeeves.py", line 104, in gene_phenos                                                                                                                                                                                        
    results = self.result_dao.get_top_per_pheno_variant_results_range(chrom, start, end)                                                                                                                                                                                       
  File "/home/mwm1/Work/pheweb/pheweb/serve/data_access/db.py", line 908, in get_top_per_pheno_variant_results_range                                                                                                                                                           
   if "maf_cases" in self.header_offset
